services:
  deaddrop:
    build: .
    image: myorg/deaddrop:latest
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    environment:
      TDX_SOCKET: /var/run/tappd.sock  
    ports:
      - "8000:8080"
    # and override the ENTRYPOINT args if you like:
    command: bash ./script.sh a a a