[package]
name = "deadbug_receiver"
version = "0.1.0"
edition = "2021"


[dependencies]
tonic = "0.8"
prost = "0.12"
prost-types = "0.12"
dialoguer      = "0.10"
rust_omr = {path = "../rust_omr", version = "0.1.0"}

[build-dependencies]
prost-build = "0.12"
tonic-build = "0.8"