[package]
name = "deadbug_detector"
version = "0.1.0"
edition = "2021"


[dependencies]
rust_omr = {path = "../rust_omr", version = "0.1.0"}
utils = {path = "../utils", version = "0.1.0"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
base64 = "0.22.1"
hex = "0.4"

